services:
  postgres:
    image: postgres:16-alpine
    container_name: eru-postgres
    environment:
      POSTGRES_DB: eru
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7EZLAbiografstol
    ports:
      - "5432:5432"
    volumes:
      - eru-postgres-data:/var/lib/postgresql/data

volumes:
  eru-postgres-data:
