package app.exceptions.enums;

public enum ApiErrorCode {
    VALIDATION_ERROR,
    AUTH_UNAUTHORIZED,
    AUTH_FORBIDDEN,
    RESOURCE_NOT_FOUND,
    DATABASE_VALIDATION,
    DATABASE_TRANSACTION_FAILURE,
    DATABASE_UNKNOWN,
    CONFIGURATION_ERROR,
    INTERNAL_ERROR
}
